# Generated by Django 4.1.3 on 2022-12-09 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.IntegerField(choices=[(0, '一般'), (1, 'M'), (2, 'E'), (3, 'D'), (4, 'J'), (5, 'C')])),
                ('grade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.IntegerField(choices=[(0, '一般'), (1, 'M'), (2, 'E'), (3, 'D'), (4, 'J'), (5, 'C')])),
                ('grade', models.IntegerField()),
                ('select', models.BooleanField()),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('credit', models.IntegerField()),
                ('url', models.URLField(blank=True)),
                ('students', models.ManyToManyField(related_name='subjects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject_register.form')),
            ],
        ),
    ]
