# Generated by Django 4.1.3 on 2022-12-09 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject_register', '0002_alter_subject_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='subject',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='subject_register.subject'),
        ),
        migrations.AlterField(
            model_name='option',
            name='title',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
